### ISSUE TITLE
mike.on('ready') never fires

### ISSUE THREAD

**Issue by jessep** [audiocogs/pitch.js-demo#5]
Was excited to see this demo, but haven't yet gotten it to work. Cloned and opened ui.html. Everything loads, but mike.on('ready') never fires. Trying to understand what's going on, but it would be awesome to get that working.

**Comment by jussi-kalliokoski** [comment]
Are you running this from the file system or a HTTP server? IIRC it won't work correctly if it's run from the file system.

**Comment by crackofdusk** [comment]
Also make sure all the libraries in /vendor are present. They are git submodules; eee http://stackoverflow.com/a/4438292 on how to get them.

**Comment by jessep** [comment]
Ah, thanks so much guys! Wasn't run on a server, forgot about flash limitations running locally. Very cool, excited to mess with this.
