### ISSUE TITLE
Cannot get the demo to work

### ISSUE THREAD

**Issue by Shantanu-Daithankar** [audiocogs/pitch.js-demo#6]
Hi!

I am trying to get this application to work for the first time but am unable to do so.

I have taken the latest libraries for fft.js, mike.js and pitch.js and put them in the required location of the directory structure as per the paths in the ui.html file.

When I run it in Chrome all I get is an image of the pitch meter which is partially covered with a white box. After that, I do not see any action - even my microphone(built into the webcam) light does not light up - which it usually does. My guess is that the issues lies with the microphone detection.

I tried debugging the javascript but there are no errors - the mike onError function is never stepped into and there are no console logs either.

It would be really helpful if I could get some help to setup this awesome app.

Thanks,
Shantanu

**Comment by crackofdusk** [comment]
Hi,

I assume you did not run the demo from a (local) web server. I added a [readme with setup instructions](https://github.com/audiocogs/pitch.js-demo/blob/master/README.md). That should get you going.
